/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calculate = new StandardCalculator();
        calculate.add(1, 1);
        
        System.out.println(calculate.getResult());

        ScientificCalculator scical = new ScientificCalculator();
        scical.squareOf(2.1);
        System.out.println(scical.squareOf(2.1));

        int result= scical.modulo(10, 2);
        System.out.println("modulo =" + result);
    }
}


